services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    init: true
    depends_on:
      - voicevox
    restart: unless-stopped
    volumes:
      - ./config/yomiagemon.yaml:/etc/yomiagemon.yaml:ro
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.14.4
    restart: unless-stopped
    expose:
      - 50021