services:
  app:
    image: ghcr.io/approvers/yomiage-mon:latest
    env_file:
      - .env
    init: true
    depends_on:
      - voicevox
    restart: unless-stopped
    secrets:
      - discord_token
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.14.4
    restart: unless-stopped

secrets:
  discord_token:
    file: .secret
